export const BASE_URL = 'http://192.168.1.41:8000/api/'
// export const BASE_URL = 'https://minscp.com/ecom/backend/api/'
export const REGISTER = `${BASE_URL}register`
export const LOGIN = `${BASE_URL}login`
export const UPDATE_PROFILE = `${BASE_URL}profile/update`
export const GET_USER_INFO = `${BASE_URL}profile/index`
export const ADD_ADDRESS = `${BASE_URL}addresses/`
export const UPDATE_ADDRESS = `${BASE_URL}addresses/`
export const DELETE_ADDRESS = `${BASE_URL}addresses/`
export const GET_CATEGORY = `${BASE_URL}categories/`
export const GET_PRODUCT = `${BASE_URL}products/`
export const GET_SECTIONS = `${BASE_URL}sections/`
export const GET_CATEGORIES = `${BASE_URL}categories/`
export const GET_EXAMPLES = `${BASE_URL}examples/`
export const GET_EXAMPLES_DASHBOARD = `${BASE_URL}dashboard/examples/`
export const ADD_EXAMPLE = `${BASE_URL}dashboard/examples/`
export const UPDATE_EXAMPLE = `${BASE_URL}dashboard/examples/`
export const DELETE_EXAMPLE = `${BASE_URL}dashboard/examples/`
export const GET_NAMES_DASHBOARD = `${BASE_URL}dashboard/names/`
export const ADD_NAME = `${BASE_URL}dashboard/names/`
export const UPDATE_NAME = `${BASE_URL}dashboard/names/`
export const DELETE_NAME = `${BASE_URL}dashboard/names/`
export const GET_LOGOS_DASHBOARD = `${BASE_URL}dashboard/logos/`
export const ADD_LOGO = `${BASE_URL}dashboard/logos/`
export const UPDATE_LOGO = `${BASE_URL}dashboard/logos/`
export const DELETE_LOGO = `${BASE_URL}dashboard/logos/`
export const GET_IMAGES_DASHBOARD = `${BASE_URL}dashboard/images/`
export const ADD_IMAGE = `${BASE_URL}dashboard/images/`
export const UPDATE_IMAGE = `${BASE_URL}dashboard/images/`
export const DELETE_IMAGE = `${BASE_URL}dashboard/images/`
export const GET_PRINT_TYPES_DASHBOARD = `${BASE_URL}dashboard/printtypes/`
export const ADD_PRINT_TYPE = `${BASE_URL}dashboard/printtypes/`
export const UPDATE_PRINT_TYPE = `${BASE_URL}dashboard/printtypes/`
export const DELETE_PRINT_TYPE = `${BASE_URL}dashboard/printtypes/`
export const GET_NAMES = `${BASE_URL}names`
export const GET_LOGOS = `${BASE_URL}logos`
export const GET_IMAGES = `${BASE_URL}images`
export const GET_PRINT_TYPES = `${BASE_URL}printtypes`
export const GET_SIZES_DIRECTIONS = `${BASE_URL}sizedirections`
export const GET_MODELS = `${BASE_URL}models`
export const GET_MATERIALS = `${BASE_URL}materials`

export const GET_CART_ITEMS = `${BASE_URL}carts`
export const ADD_TO_CART = `${BASE_URL}carts`
export const REMOVE_FROM_CART = `${BASE_URL}carts`


export const GET_CLIENTS = `${BASE_URL}dashboard/users/`
export const GET_CLIENT = `${BASE_URL}dashboard/users/`
export const UPDATE_CLIENT = `${BASE_URL}dashboard/users/`

export const GET_PRODUCTS_DASHBOARD = `${BASE_URL}dashboard/products`
export const ADD_PRODUCT = `${BASE_URL}dashboard/products/`
export const UPDATE_PRODUCT = `${BASE_URL}dashboard/products/`
export const UPDATE_COLOR = `${BASE_URL}dashboard/colors/`
export const DELETE_COLOR = `${BASE_URL}dashboard/colors/`
export const GET_PRODUCT_DASHBOARD = `${BASE_URL}dashboard/products/`
export const GET_CATEGORIES_DASHBOARD = `${BASE_URL}dashboard/categories/`
export const GET_SHIPPING_COMPANIES = `${BASE_URL}dashboard/shippingcompanies/`
export const GET_SHIPPING_COMPANY = `${BASE_URL}dashboard/shippingcompanies/`
export const ADD_SHIPPING_COMPANY = `${BASE_URL}dashboard/shippingcompanies/`
export const UPDATE_SHIPPING_COMPANY = `${BASE_URL}dashboard/shippingcompanies/`
export const DELETE_SHIPPING_COMPANY = `${BASE_URL}dashboard/shippingcompanies/`

export const ADD_ORDER = `${BASE_URL}orders/`
export const GET_ORDERS = `${BASE_URL}orders/`